# Generated by Django 2.1 on 2018-08-13 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique', models.TextField()),
                ('target', models.TextField()),
                ('discover', models.TextField()),
                ('documents', models.NullBooleanField()),
                ('just_an_idea', models.NullBooleanField()),
                ('product_specs', models.NullBooleanField()),
                ('product_sample', models.NullBooleanField()),
                ('product_no_branding', models.NullBooleanField()),
                ('product_need_marketing', models.NullBooleanField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toys.Category')),
                ('division1_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toys.Division')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='toys.Status')),
            ],
        ),
    ]
